### ISSUE TITLE
Wrong color for fetches

### ISSUE THREAD

**Issue by Selid** [Haven-King/Proximity#18]
Prismatic Vista and Fabled Passage at least have the grey-brown color while they should be golden. Any colors land are okay though.

**Comment by Haven-King** [comment]
The part that makes this very hard is that WoTC's stance on what lands should have what color frames is rather ambiguous. Evolving Wilds for instance uses effectively the exact same wording as Prismatic Vista and Fabled Passage, but it is grey rather than gold. Without a reliable way to infer frame color, I'm not sure what I can do other than offer a way to set the color for any card manually.

**Comment by Selid** [comment]
We had this discussion month ago on the discord, turns out it's the rarity. If you can fetch any basic, and you are rare or above, then gold it is. Otherwise brown.
